# mediator needs secrets from multiple namespaces - easier to just add clusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ print .Release.Name "-" .Values.rhmediator.appName "-secret-reader-rb" | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "data-collecting.serviceAccountName" (list $ .Values.rhmediator) | quote}}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "data-collecting.clusterRoleName" (list $ .Values.rbac.secretReaderBaseName) | quote }}
  apiGroup: rbac.authorization.k8s.io