apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ print .Release.Name "-" .Values.rhpoller.appName "-secret-reader-rb" | quote }}
  namespace: {{ .Values.rhpoller.args.secretNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "data-collecting.serviceAccountName" (list $ .Values.rhpoller) | quote}}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "data-collecting.clusterRoleName" (list $ .Values.rbac.secretReaderBaseName) | quote }}
  apiGroup: rbac.authorization.k8s.io