{{- with .Values.rhpoller }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-collecting.fullname" (list $ .) }}
  labels:
    {{- include "data-collecting.labels" $ | nindent 4 }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .appName | quote }}
  template:
    metadata:
      labels:
        app: {{ .appName | quote }}
    spec:
      serviceAccountName: {{ include "data-collecting.serviceAccountName" (list $ .) | quote }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: rh-poller
          image: "{{ .image.repository }}:{{ .image.tag | default "current" }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          args:
            {{- include "data-collecting.transformArgs" .args | indent 12 }}
{{- end -}}                  
