apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ print .Release.Name "-" .Values.rhpoller.appName "-pod-reader-crb"  | quote}}
subjects:
- kind: ServiceAccount
  name: {{ include "data-collecting.serviceAccountName" (list $ .Values.rhpoller) | quote }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "data-collecting.clusterRoleName" (list $ .Values.rbac.podReaderBaseName) }}
  apiGroup: rbac.authorization.k8s.io