apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "data-collecting.clusterRoleName" (list $ .Values.rbac.secretReaderBaseName) | quote }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch