apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "data-collecting.serviceAccountName" (list $ .Values.eventhubRecevier) | quote }}
  labels:
    {{- include "data-collecting.labels" . | nindent 4 }}